### ISSUE TITLE
Epic: Coordinators can activate the volunteers profile

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#104]
### Story

As a **Coordinator**, I can **look at new profiles and consider them for old projects and then activate them** so that I can **check for spam and see what is newly available**.

### Acceptance Criteria

- Activation of volunteers by coordinators is working

### Tasks

- [ ] Set up template
- [ ] set up url
- [ ] code views
- [ ] check it is working
