### ISSUE TITLE
User Story: Index.html

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#12]
### Story

As a **user**, I can **arrive on an interesting page** so that I can **feel excited to continue/volunteer**.

### Acceptance Criteria

- Fully functioning page with links operational
- Suitable image for each activity
- Suitable description for each activity

### Tasks

- [ ] connect to base.html
- [ ] Each activity should have an image
- [ ] Each activity should have some descriptive text
