### ISSUE TITLE
User Story: Validators

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#14]
### Story

As a **player**, I can **do some action** so that I can **achieve some goal**.

### Acceptance Criteria

- No problems on HTML validator
- No problems on CSS validator
- Meets PEP8 requirements
- 
### Tasks

- [ ] check on HTML validator
- [ ] check on CSS validator
- [ ] Check on PEP8 linter
