### ISSUE TITLE
User Story: How volunteering works page

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#15]
### Story

As a **user**, I can **read information about volunteering on this system** so that I can **understand the charity**.

### Acceptance Criteria

- Informative/Visually enticing how it works page based on base.html

### Tasks

- [ ] Create how it works page
- [ ] put text on how it works page
- [ ] Add relevant links throughout the text
