### ISSUE TITLE
User Story: mentor meeting - middle

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#17]
### Story

As a **developer**, I can **talk through the project** so that I can **get experienced advice**.

### Acceptance Criteria

- Meeting information provided to mentor before meeting
- 45 minute meeting with mentor

### Tasks

- [ ] provide information prior to meeting to mentor
- [ ] arrange suitable date for meeting
- [ ] 45 minute meeting about project

**Comment by RachWalm** [comment]
Meeting set for 13:00 on Friday.
