### ISSUE TITLE
User Story: mentor meeting before submission

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#18]
### Story

As a **developer**, I can **run through my project with someone with experience** so that I can **gain an experienced opinion on my work**.

### Acceptance Criteria

- 45 minute meeting gaining information on what I need to do before submission

### Tasks

- [ ] Complete most of the project
- [ ] Prepare to work through with mentor and sent pre-information
- [ ] Set up meeting
- [ ] 45 minute meeting
