### ISSUE TITLE
User Story: White noise add on for static images

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#19]
### Story

As a **developer**, I can **use whitenoise** so that I can **store static images**.

### Acceptance Criteria

- static images are stored and retrieved using whitenoise

### Tasks

- [ ] look into whitenoise
- [ ] add whitenoise to the project
- [ ] put static images on white noise

**Comment by RachWalm** [comment]
#100 will put the images across to whitenoise once the development has been completed and so it won't be changed.
