### ISSUE TITLE
User Story: Planning board

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#2]
### Story

As a **Developer**, I can **see the plan on the project board** so that I can **see the progress of the project and what needs doing**.

### Acceptance Criteria

- All foreseen activities have an associated issue on the project board
- All activities have a priority
- Where reasonable set a milestone and put into the appropriate column

### Tasks

- [ ] Put all intended tasks into issues on Git 
- [ ] Assign them a priority
- [ ] Assign Milestones to ones that can be predicted
- [ ] Set the first iteration into the to do column
