### ISSUE TITLE
User Story: complete README

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#23]
### Story

As a **future developer**, I can **read the README ** so that I can **understand the software**.

### Acceptance Criteria

- Completed proof read README
- all links work

### Tasks

- [x] Complete README to good standard
- [x] get proof read
- [x] check all links work
