### ISSUE TITLE
User Story: complete TESTING document

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#24]
### Story

As a **future developer**, I can **read the TESTING** so that I can **understand how the software should work and how it did**.

### Acceptance Criteria

- Complete TESTING document available
- proof read
- all links work

### Tasks

- [ ] Document all testing
- [ ] get it proof read
- [ ] check all links work
