### ISSUE TITLE
User Story: availability model

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#26]
### Story

As a **volunteer**, I can **have a place to store my preferences** so that I can **be matched to appropriate timeslots**.

### Acceptance Criteria

- Multiple choice storage of available timeslots
- All appropriate timeslots can be chosen from a list when that functionality is implemented
- length of time information can be stored

### Tasks

- [ ] Develop list of timeslots
- [ ] Set up names, text to show and abbreviations to store
- [ ] length of time available for information stored
