### ISSUE TITLE
User Story: index.html veiw and 

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#28]
### Story

As a **user**, I can **view index.html** so that I can **arrive at the landing page and decide what to do**.

### Acceptance Criteria

- views.py has appropriate code
- urls.py has the path in it
- template created and meets user story #12 
- page functions as expected

### Tasks

- [ ] create code in view.py
- [ ] connect up urls
- [ ] #12 has content for the index
