### ISSUE TITLE
User Story: set up allauth

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#29]
### Story

As a **volunteer/coordinator**, I can **register/login** so that I can **use the site functionality**.

### Acceptance Criteria

- Allauth registration and login working
- links in the navigation bar

### Tasks

- [ ] Set up different registrations for volunteers and coordinators
- [ ] have registers/logins send volunteers to the correct page
- [ ] Have the navigation bar available on every page
- [ ] Use all auth

**Comment by RachWalm** [comment]
Still need to get the coordinators register and log in sent to correct page
