### ISSUE TITLE
User Story: flash messages

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#30]
### Story

As a **user**, I can **see confirmation of the action I have taken** so that I can **know that the action I took has been processed**.

### Acceptance Criteria

- log in flash message at the appropriate time for an appropriate length of time
- log out flash message at the appropriate time for an appropriate length of time
- submitting profile flash message at the appropriate time for an appropriate length of time

### Tasks

- [ ] Flash message for login
- [ ] Flash message for logout
- [ ] Flash message for submitting a profile for approval
