### ISSUE TITLE
User Story: volunteer register with site

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#31]
### Story

As a **volunteer**, I can **register with the site** so that I can **use the functionality**.

### Acceptance Criteria

- Registration saves and is visible in the admin view
- Registration takes the username, e-mail and password
- Registration takes the volunteer to the profile page for them to create a profile

### Tasks

- [ ] allauth registration set up
- [ ] This is one of the tasks that needs to be done
- [ ] This is one of the tasks that needs to be done
