### ISSUE TITLE
User Story: volunteer can update profile

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#38]
### Story

As a **player**, I can **do some action** so that I can **achieve some goal**.

### Acceptance Criteria

- This is an example of something that must be achieved for the story to be considered complete
- This is an example of something that must be achieved for the story to be considered complete
- This is an example of something that must be achieved for the story to be considered complete

### Tasks

- [ ] This is one of the tasks that needs to be done
- [ ] This is one of the tasks that needs to be done
- [ ] This is one of the tasks that needs to be done
### Story

As a **volunteer**, I can **fill out the profile form** so that I can **be available for various activities**.

### Acceptance Criteria

- Form displays all the relevant information in it's current state from the database
- Form submits new information/ all information to the database
- All relevant view, models, templates and urls have been set up/connected

### Tasks

- [ ] Get the information from the database for that profile to display
- [ ] resubmit all the data to the database when the volunteer clicks submit.
- [ ] fill out the view.py and urls.py
