### ISSUE TITLE
User Story: volunteer can read their own profile

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#39]
### Story

As a **volunteer**, I can **see my details not in a form** so that I can **be confident of the information that the organisation holds about me**.

### Acceptance Criteria

- Information on the signed in user is displayed in a user friendly display rather than filling out a form

### Tasks

- [ ] Set up template for user to see their information
- [ ] connect all relevant urls.py
- [ ] complete view.py
