### ISSUE TITLE
User Story: volunteer profile deletion

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#40]
### Story

As a **Volunteer**, I can **delete my profile** so that I can **stop volunteering and remove my data from the system**.

### Acceptance Criteria

- Profile deletion functionality is easy for the volunteer to access
- a warning that it is a permanent delete not inactivation warning forces them to agree
- Profile is deleted upon request

### Tasks

- [ ] Set up deletion functionality
- [ ] Set up pop up to force them to confirm that they want to delete it
- [ ] data is no longer in the system once the volunteer has deleted it.

**Comment by RachWalm** [comment]
See stories #89 and #64  and #40
