### ISSUE TITLE
User Story: Use decorators in admin.py

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#49]
### Story

As a **developer**, I can **use decorators instead of admin.site.register in admin.py** so that I can **write more pythonic simpler code**.

### Acceptance Criteria

- changed code still works with all models registered for both coordinator and volunteer.

### Tasks

- [ ] Find out more about decorators
- [ ] Change the code in admin.py coordinator
- [ ] Change the code in admin.py volunteer
