### ISSUE TITLE
User Story: Bootstrap

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#51]
### Story

As a **developer**, I can **use bootstrap** so that I can **format my site**.

### Acceptance Criteria

- Bootstrap used appropriately to format and make the site accessible

### Tasks

- [ ] Look into bootstrap
- [ ] Decide which features and formats I want to use
- [ ] Implement these features into the site
