### ISSUE TITLE
Task : set up allauth

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#60]
### Story

As a **developer**, I can **use allauth** so that I can **for my authentication**.

### Acceptance Criteria

- Basic allauth set up and working

### Tasks

- [ ] pip install allauth
- [ ] put allauth in settings.py etc.
- [ ] test allauth is working

**Comment by RachWalm** [comment]
user story #29
