### ISSUE TITLE
Epic: Volunteer reads their profile

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#63]
### Story

As a **Volunteer**, I can **look at the preferences I have chosen** so that I can **be confident they are correct**.

### Acceptance Criteria

- A page displays the preferences in a user friendly format

### Tasks

- [ ] Create a page that shows preferences in a user friendly format
- [ ] Get this page to collect the correct information 
- [ ] Test page is getting correct information and displaying it in a user friendly format
