### ISSUE TITLE
Epic : coordinator can search the profiles to find someone to do the volunteering

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#68]
### Story

As a **coordinator**, I can **search for a suitable volunteer** so that I can **match the activity to a volunteer**.

### Acceptance Criteria

- Coordinator search function works

### Tasks

- [ ] set up coordinator search function page
- [ ] set up search functionality
- [ ] Test search function
