### ISSUE TITLE
Bug: Can only select one day and timeslot

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#81]
### Story

As a **volunteer**, I can **select multiple days and timeslots** so that I can **select all that are applicable**.

### Acceptance Criteria

- Volunteers can select multiple days and timeslots

### Tasks

- [ ] find out how to set it to mulitple days and timeslots
- [ ] implement mulitple days and timeslots
- [ ] test mulitple days and timeslots

**Comment by RachWalm** [comment]
Not sure why it wasn't working, but copied the code from another app in the project and set it up again and it started to work. Suspect a spelling mistake or typo as looked the same.
