### ISSUE TITLE
User Story:coordinator registration and log in direct to correct page

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#84]
### Story

As a **coordinator**, I can **register/login and it progresses me to the right page** so that I can **perform coordinator activities**.

### Acceptance Criteria

- registration and login process follows correct pages route

### Tasks

- [x] Create the correct templates urls and views
- [x] get it all linked up and working
- [x] test these pages go to the correct place

**Comment by RachWalm** [comment]
see #67 and #29
