### ISSUE TITLE
Epic: if user isn't logged in but URL for a logged in page typed send to error page

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#85]
### Story

As a **site user**, I can **type the url but not be logged in ** so that I can **see a useful information error page rather than url not found etc.**.

### Acceptance Criteria

- each url if typed while logged out that can only be accessed logged in sends user to appropriate information on error page.

### Tasks

- [ ] set up is_autheticated in the webpages that need to be logged in to see
- [ ] set up webpages explain why they can't access that page templates
- [ ] connect up pages with urls and views (and models?)
