### ISSUE TITLE
Task: deletion functionality in place

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#89]
### Story

As a **developer**, I can **have the basic functionality in place for delete** so that I can **work on finer details of delete such as check intended to delete**.

### Acceptance Criteria

- Template must be present
- urls path present
- view present

### Tasks

- [ ] set up template
- [ ] fill out urls
- [ ] set up a view function

**Comment by RachWalm** [comment]
Very basic functionality no checking that they meant to delete or anything - just does the function when the button is clicked. Additional functionality will be required.

**Comment by RachWalm** [comment]
See stories #64  and #40
