### ISSUE TITLE
User Story: ensure that when you log in you get sent to right place

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#93]
### Story

As a **user**, I can **log in** so that I can **be sent to the correct page for the stage I am at**.

### Acceptance Criteria

- If I am a volunteer and don't have a profile it sends me to fill out a profile
- If I am a volunteer with a profile it sends me to view my profile
- If I am a coordinator it sends me to the correct area depending on if I am approved.

### Tasks

- [x] set up urls to add if profile needed
- [x] set up urls to read if profile available
- [x] check what happens if only partial profile saved and set up appropriate urls
- [x] set up coordinator pending urls
- [x] set up coordinator dashboard urls
- [x] set up coordinator dashboard templates without filling
- [x] set up coordinator views without functionality
- [x] set up tickets to fill template and views with functionality
