### ISSUE TITLE
User Story: Coordinator can update their profile

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#95]
### Story

As a **Coordinator**, I can **update/read my profile** so that I can **have personalised information and permissions**.

### Acceptance Criteria

- Coordinator can update/read information to their profile and saves appropriately

### Tasks

- [ ] set up update/read coordinator profile template
- [ ] set up update/read coordinator profile urls
- [ ] set up view for update/read coordinator profile

**Comment by RachWalm** [comment]
Coordinators can update profiles, but it appears to pick a profile. I haven't put in the functionality to choose the correct profile yet.

**Comment by RachWalm** [comment]
Update has been completed. Still need to do a page for read. May add more things that can be updated to the profile but basics in place.

**Comment by RachWalm** [comment]
Decided not to do an update on which charities a coordinator has as it can be done from the charity end and although this would be a nice feature it is value adding not necessary so won't be included at this stage. all other updates can be performed. Entire profile can be read.
