### ISSUE TITLE
User Story: add more flash messages 

### ISSUE THREAD

**Issue by RachWalm** [RachWalm/VolunteerVillage#97]
### Story

As a **user**, I can **receive feedback from actions** so that I can **know what is happening**.

### Acceptance Criteria

- All relevant actions have flash messages
- This is tested and working

### Tasks

- [ ] Look through the actions and see which ones would benefit from flash messages
- [ ] Add flash messages to those actions
- [ ] test the flash messages occur when expected with correct message colour etc.

**Comment by RachWalm** [comment]
added flash messages to charity and coordinator features but still need testing and other flash messages adding.
